name: Automatic Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  automatic_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Update apt-get
        run: sudo apt-get update -y

      - name: Install dependencies
        run: sudo apt-get install -y gcc libcunit1 libcunit1-doc libcunit1-dev valgrind
        
      - name: Compile Source Code
        run: gcc -Wall -Wextra -pedantic -g ./inluppar/inlupp1/hash_table.c ./inluppar/inlupp1/hash_table_tests.c -o ./inluppar/inlupp1/test.out -lcunit

      - name: Run Tests
        run: valgrind --leak-check=full -s ./inluppar/inlupp1/test.out